/*

	Author: $kylar

	GRR Link: http://www.gta-sarp.com/forums/showthread.php?302113-Development-Related-Aaron_Steel-s-Request

*/

// Aaron Steel's SQL ID //
#define AARON_STEEL_ID 152639

#include "../gamemodes/inc/donor/Donor_scripts/Aaron_Steel_152639/Assistant.inc"
#include "../gamemodes/inc/donor/Donor_scripts/Aaron_Steel_152639\Elevator.inc"
#include "../gamemodes/inc/donor/Donor_scripts/Aaron_Steel_152639\dispenser.inc"
#include "../gamemodes/inc/donor/Donor_scripts/Aaron_Steel_152639\bizcard.inc"