//mysql info
new sqlShopConnection; //shop
new const sqlShopHostname[] = "localhost";
new const sqlShopUsername[] = "15_server";
new const sqlShopPassword[] = "88gqvSGMkrvM5Z";
new const sqlShopDatabase[] = "15_serverdb";
new const sqlShopPort = 63306;
new bool:sqlShopAutoReconnect = true;
new const sqlShopPoolSize = 2;

new sqlGameConnection; //game
new const sqlGameHostname[] = "localhost";
new const sqlGameUsername[] = "15_server";
new const sqlGamePassword[] = "88gqvSGMkrvM5Z";
new const sqlGameDatabase[] = "15_serverdb";
new const sqlGamePort = 3306;
new bool:sqlGameAutoReconnect = true;
new const sqlGamePoolSize = 3;

// BETA
// new const sqlBetaHostname[] = "localhost";
// new const sqlBetaUsername[] = "15_server";
// new const sqlBetaPassword[] = "88gqvSGMkrvM5Z";
// new const sqlBetaDatabase[] = "15_serverdb";

// localhost
new const sqlBetaHostname[] = "localhost";
new const sqlBetaUsername[] = "15_server";
new const sqlBetaPassword[] = "88gqvSGMkrvM5Z";
new const sqlBetaDatabase[] = "15_serverdb";


