//include the old donor scripts

/*
 _____                            _____           _       _       
|  __ \                          / ____|         (_)     | |      
| |  | | ___  _ __   ___  _ __  | (___   ___ _ __ _ _ __ | |_ ___ 
| |  | |/ _ \| '_ \ / _ \| '__|  \___ \ / __| '__| | '_ \| __/ __|
| |__| | (_) | | | | (_) | |     ____) | (__| |  | | |_) | |_\__ \
|_____/ \___/|_| |_|\___/|_|    |_____/ \___|_|  |_| .__/ \__|___/
                                                   | |            
                                                   |_|   
												   
												   
	Review: ./README.md
	Donors have their own folder, where the folder is named [FULL_NAME-INGAME]-[SQLID]
	
	Best regards,
	Fred.
*/

/*
		DONOR PROJECTS
			* Donor projects are included below (one per donor)
*/

/*
	Shared varibles
*/

// Donor Checkpoints(for use in the CP variable)
enum
{	
	CHECKPOINT_RUTHLESS, //Keven Ruthless
	CHECKPOINT_DESMOND, //Desmond DeSantos
    CHECKPOINT_OUTPOST, //Eric Daxono
    CHECKPOINT_FLETCHER, //Nick Fletcher
    CHECKPOINT_KLASHW //Klash Woods
};

#include "inc/donor/Primitivo_Bienvenida-941"
#include "inc/donor/Sean_Johnson-859"
#include "inc/donor/Thomas_Breslin-72741"
#include "inc/donor/Kevin_Burke-35711.inc"
#include "inc/donor/JonasBlue-1423.inc"
#include "inc/donor/John_McClain-13040.inc"
// #include "inc/donor/James_Fairland-202.inc" Needs to be called within main gm to avoid undefined symbol errors
#include "inc/donor/Mariela_Tucci-91115.inc" 


#include "inc/donor/donorScripts.inc"
//#include "./Violetta_Carlevaro-4693/core"
